version: 0.2

env:
  git-credential-helper: yes
  secrets-manager:
    key: github-ray-bci:GITHUB-USER
    value: github-ray-bci:GITHUB-PASSWORD

phases:

  build:
    commands:
      - export TAG_VERSION=`awk '/VERSION/{print $NF}' lib/version.rb | sed -e "s/^'//" -e "s/'$//"`
      - echo $TAG_VERSION
  post_build:
    commands:
      - git tag $TAG_VERSION
      - git push --tags http://$key:$value@github.com/beyondsoft-na/convergdb.git