version: 0.2

env:
  git-credential-helper: yes
  secrets-manager:
    key: github-ray-bci:GITHUB-USER
    value: github-ray-bci:GITHUB-PASSWORD

phases:
  install:
    commands:
      - git config --global credential.helper
      - git config --global credential.UseHttpPath true
  build:
    commands:
      - ls
      - echo $key
      # - mv ${CODEBUILD_SRC_DIR}/src.jar ${CODEBUILD_SRC_DIR}/spaces_gem.jar
      # - cd ${CODEBUILD_SRC_DIR} && git clone https://git-codecommit.us-west-2.amazonaws.com/v1/repos/convergdb_integration_tests 
      # - sh ${CODEBUILD_SRC_DIR}/convergdb_integration_tests/test_01/integrationtest.sh
  post_build:
    commands:
      - export TAG_VERSION=`awk '/VERSION/{print $NF}' lib/version.rb | sed -e "s/^'//" -e "s/'$//"`
      - echo $TAG_VERSION
      - git tag $TAG_VERSION
      - git tag
      - git push --tags http://$key:$value@github.com/beyondsoft-na/convergdb.git
      # - cd ${CODEBUILD_SRC_DIR}/convergdb_integration_tests/test_01 && sh destroy.sh
      # - echo "Integration Test completed on:" `date`
# artifacts:
#   files:
#     - spaces_gem.jar
#     - bin/*
